version: '3.7'
# you need to run the command `xhost local:root` before launching 'sudo docker-compose up'
services:
  pacman_dqn:
    working_dir: /usr/src/app
    build:
      context: ./
      dockerfile: Dockerfile
    image: python-pacman-dqn
    command: "sh -c 'python pacman.py -p PacmanDQN -n ${TOTAL_GAMES_NB} -x ${TRAINING_GAMES_NB} -l ${LAYOUT}'"
    volumes:
      - ./:/usr/src/app
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
    env_file: .env
    environment:
      - DISPLAY
      - XAUTHORITY=/tmp/.docker.xauth
    stdin_open: true
    tty: true
